### ISSUE TITLE
Browser decryption failed with "Bad MAC"

### ISSUE THREAD

**Issue by pranavburnwal** [bitchan/eccrypto#63]
The decryption failed with the "Bad MAC" error on the browser. This is happening on 'eth-crypto' module which uses this as a dependency.
This case happens only like ~ 1/300 cases. Rest 299 decrypt with perfectly fine on the browser itself.

Even the cases that failed on browser are being able to decrypt on Node easily without any problems. Points me to check the newer builds.
We are using Webpack and have been using this same module the same version for more than a year. and this started recently. I am trying to trace right now but any help would be appreciated.

Thank you for your time.

Ref ticket for Eth-crypto: https://github.com/pubkey/eth-crypto/issues/281

**Comment by JBaczuk** [comment]
Without more info, it is hard to be helpful, but it sounds similar to this issue, which appears to have been an environment issue: https://github.com/bitchan/eccrypto/issues/52

**Comment by pranavburnwal** [comment]
Please share what more info I can provide?

**Comment by pranavburnwal** [comment]
So we have packed the module in a webpack deployment. There is no compilation error.
We use the same module version In server and browser. The same code with the same parameters decrypts on Server(nodeJS) but does not decrypt on the browser. 
Again on more testing the whole the cases are rare like 1/300 ~ 1/500 cases. 

The same code and modules are used for all of those cases but a few in thousand fail.

**Comment by JBaczuk** [comment]
Without anything to reproduce this issue, I'm afraid I'm not sure how to help. Are you using the latest browser versions? Which browser are you using. is there any pattern with the cases that fail (like [character length](https://github.com/bitchan/eccrypto/issues/62))

**Comment by pranavburnwal** [comment]
Not sure about that, The data all cases are like similar in structure and format. 
I stopped working on that for now. I will retry over this weekend. 
Is there any way I can share the base with you so you can replicate it? The problem is whenever I manually encrypt it always decrpts easily. I manually cannot do 500 cases for test

**Comment by ibudisteanu** [comment]
I get a lot of BAD MAC on nodejs decryption using encryption from Browser. Probably about 10% of (priv, pub) pairs

**Comment by pranavburnwal** [comment]
> 
> 
> I get a lot of BAD MAC on nodejs decryption using encryption from Browser. Probably about 10% of (priv, pub) pairs

Yeah, any luck on debugging? Anything special you are trying?

**Comment by fredeno** [comment]
We are facing a similar problem when data is encrypted in Browser and decrypted in Node.js, and vice versa.
This works fine most of the time but we see some "Bad MAC" failures occuring. Failure probability is arround 1 for 300 occurences, even when encrypting the same data in a loop with the same key (using eccrypto version 1.1.6).

When decrypt failure occurs on Node, executing the decrypt function for browser works ! In other words, Node and Browser implementation do not seem to be plainly compatible.

**Comment by AgentRX** [comment]
Hi! Here is stack trace of error:
`{"type":"Error","message":"Bad MAC","stack":"Error: Bad MAC\n    at assert (/home/node/node_modules/eccrypto/browser.js:16:11)\n    at /home/node/node_modules/eccrypto/browser.js:258:5\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"},`

Here is data to reproduce Bad MAC:
`{"iv":"YqX1RJMwOldgk60iYE4xiw==","ephemPublicKey":"BJh5d3wGrtVCnTw7BYdBca3e+FW4XRq8U/y3IlnBwnR95euUQZIu1na1GwD4BJeX0zA2yamVngnsII8gyo0AApQ=","mac":"OYGjpPWkCaqCjMdAexn/GGhhuUqVto7FYPgXt9OOtyw=","encoding":"base64","algo":"ECIES","ciphertext":"awAMbQmDmr0TWrxDRLRPCuOKwGfjyzwP5oFvNIcizoqM87rrTZoNGd/8f2e+naeYwKEyv9UuE9btc1jKfJq9N/C+7i+4/j61EQIfnkVE0A9nJjf5jfOZSb7FzPaNB/YIJvHRpnyAVbX8S55NeHnemVg5zHPxkA2C4e5vvBJjdda1VffAlZ17rmAxBtNxrGRfuBME2TcjuN9KvjBjYblrXgyYRMT0eIth+gdxWrudJKM="}}\""`

"key":"gX7jM+34dQLfDSbO3vMBlAu3m+vRn2Es9+NUGpZSW+w="

**Comment by zkguru** [comment]
We found the possible root cause related to this issue, please refer to PR #96 for more information.
